import * as THREE from "https://unpkg.com/three@0.164.1/build/three.module.js";
import { HOLES_PER_TOURNAMENT, FPS_BASE_MOUSE_SENSITIVITY } from "./constants.js";

export const game = {
  phase: "menu",
  role: "solo",
  localIndex: 0,
  room: "",
  connected: false,
  currentPlayer: 0,
  holeIndex: 0,
  holeScores: Array.from({ length: 2 }, () => Array(HOLES_PER_TOURNAMENT).fill(null)),
  strokesThisHole: [0, 0],
  aimAngle: -Math.PI / 4,
  aimPower: 0,
  dragging: false,
  dragStart: { x: 0, y: 0, angle: 0 },
  ballMoving: false,
  golfAimPoint: new THREE.Vector3(),
  golfShotDir: new THREE.Vector3(1, 0, 0),
  golfResolveToken: 0,
  fpsMockStatic: false,
  fpsMapIndex: 0,
  fpsMapWins: [0, 0],
  fpsKillWins: [0, 0],
  fpsRoundWinner: null,
  fpsMatchOver: false,
  countdown: 0,
  result: null,
  lastSend: 0,
  lastShotAt: 0,
  activeWeapon: "gun",
  meleeSwingTimer: 0,
  primaryWeapon: "rifle",
  weaponSwapTimer: 0,
  weaponSwapCommitted: true,
  pendingActiveWeapon: "gun",
  pendingPrimaryWeapon: "rifle",
  ammo: { pistol: 7, rifle: 25, sniper: 5 },
  lastKilledBy: "",
  killNoticeTimer: 0,
  reloading: false,
  reloadTimer: 0,
  inspectTimer: 0,
  jumpCooldown: 0,
  healCooldown: 0,
  grenadeCooldown: 0,
  radarCooldown: 0,
  radarTimer: 0,
  slideTimer: 0,
  slideCooldown: 0,
  weaponSelectTimer: 0,
  fpsMode: "standard",
  randomTournament: false,
  randomWeapon: "pistol",
  randomLoadout: null,
  maxHealth: 100,
  fpsCustomMap: null,
  fpsImportedAssetUrl: "",
  buildMode: false,
  buildCursor: null,
  visualRecoil: 0,
  lastShotPosition: new THREE.Vector3(),
  golfFalling: false
};

export const input = {
  keys: new Set(),
  pointerLocked: false,
  yaw: 0,
  pitch: 0,
  aiming: false,
  shootHeld: false,
  golfChargeDir: 1,
  mouseSensitivity: FPS_BASE_MOUSE_SENSITIVITY,
  slideKeyWasDown: false
};

export const world = {
  golfRoot: new THREE.Group(),
  arenaRoot: new THREE.Group(),
  courseRoot: new THREE.Group(),
  coursePieces: [],
  icePatches: [],
  bumpers: [],
  mounds: [],
  obstacles: [],
  platforms: [],
  arenaFloors: [],
  arenaSpawnPoints: [],
  ball: null,
  ballVel: new THREE.Vector3(),
  cup: null,
  golfAimArrow: null,
  weapon: null,
  meleeWeapon: null,
  weaponTip: null,
  playerMeshes: [],
  lasers: [],
  grenades: [],
  explosions: []
};

export const fps = {
  players: [
    { pos: new THREE.Vector3(-42, 1, 0), vel: new THREE.Vector3(), acc: new THREE.Vector3(), yaw: 0, pitch: 0, health: 100, grounded: false, primaryWeapon: "pistol" },
    { pos: new THREE.Vector3(42, 1, 0), vel: new THREE.Vector3(), acc: new THREE.Vector3(), yaw: Math.PI, pitch: 0, health: 100, grounded: false, primaryWeapon: "pistol" }
  ],
  arenaHalf: 56,
  gravity: -30,
  startedAt: 0
};
